owner: tava4Tech
repo: law-suite-uptime
user-agent: tava4Tech

sites:
  - name: Law Suite Platform (Prod)
    url: https://app.law-suite.de
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: Law Suite Platform (Dev)
    url: https://app.dev.law-suite.de
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 301
      - 302

assignees:
  - haiderqaizarhussain

skipHomepageUpdate: true
skipDescriptionUpdate: true
skipTopicsUpdate: true

workflowSchedule:
  uptime: "*/15 * * * *"
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
